use std::env;
use std::fs::File;
use std::io::{Error, Write};
use std::process::Command;

const RESOLVCONF_HEAD_PATH: &str = "/etc/resolvconf/resolv.conf.d/head";

const DEFAULT_TEMPLATE: &str = "
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run \"systemd-resolve --status\" to see details about the actual nameservers.
";

const DNS_SERVER_1_ADDR: &str = "94.140.14.14";
const DNS_SERVER_2_ADDR: &str = "94.149.15.15";

const ADGUARD_DNS_SERVER_CONFIG: &str = "
# AdGuard DNS 
# https://adguard-dns.com/en/public-dns.html
nameserver 94.140.14.14
nameserver 94.149.15.15
";

const HELP_MESSAGE: &str = "
Usage: sudo rslvconf [options...]

        --activate      Activate AdGuard DNS server 
        --deactivate    Deactivate AdGuard DNS server 
        --status        Shows wether AdGuard DNS server is activated or not
        --verbose       Add verbose output to `--activate` and `--deactivate` commands
        --help          Display the current help message
";

fn main() -> Result<(), Error> {
    let mut file = File::create(RESOLVCONF_HEAD_PATH)?;
    let args: Vec<_> = env::args().collect();

    match args.len() {
        1 => println!("{}", HELP_MESSAGE),
        _ => match &args[1][..] {
            "--help" => println!("{}", HELP_MESSAGE),
            "--activate" | "activate" => activate_adguard_dns(&mut file),
            "--deactivate" | "deactivate" => deactivate_adguard_dns(&mut file),
            "--status" | "status" => show_status(),
            _ => eprintln!("Unknown argument. Try `rslvconf --help` for more information"),
        },
    }

    Ok(())
}

fn activate_adguard_dns(file: &mut File) {
    write_default_template_with_adguard_dns(file);
    update_resolvconf();
}

fn deactivate_adguard_dns(file: &mut File) {
    write_default_template(file);
    update_resolvconf();
}

fn show_status() {
    let output = std::process::Command::new("nslookup")
        .arg("wikipedia.org")
        .output()
        .expect("failed to execute nslookup");

    if let Ok(output_as_string) = String::from_utf8(output.stdout) {
        if output_as_string.contains(&DNS_SERVER_1_ADDR.to_string())
            || output_as_string.contains(&DNS_SERVER_2_ADDR)
        {
            println!("ADGUARD DNS is activated")
        } else {
            println!("ADGUARD DNS is deactivated")
        }
    } else {
        eprintln!("nslookup is not installed or could not lookup wikipedia.org")
    };
}

fn write_default_template_with_adguard_dns(file: &mut File) {
    let content = format!("{} {}", DEFAULT_TEMPLATE, ADGUARD_DNS_SERVER_CONFIG);
    write!(file, "{}", content).expect("failed to write default template");
}

fn write_default_template(file: &mut File) {
    write!(file, "{}", DEFAULT_TEMPLATE).expect("failed to write default template");
}

fn update_resolvconf() {
    Command::new("resolvconf")
        .arg("-u")
        .output()
        .expect("failed to update resolvconf");
}
